k9s:
  cluster: gke_speedscale-demos_us-central1_kraken
  namespace:
    active: kraken-2250193928-replay-loadtest
    lockFavorites: false
    favorites:
      - kraken-2250193928-replay-loadtest
      - speedscale
      - default
      - kraken-speedctl-windows
      - kraken-generator-perf-sla-1764779894
      - kraken-generator-perf-sla-1764774731
  view:
    active: v1/namespaces
  featureGates:
    nodeShell: false
  proxy: null
