k9s:
  cluster: gke_speedscale-demos_us-central1_kraken
  namespace:
    active: speedscale
    lockFavorites: false
    favorites:
      - gke-managed-cim
      - default
      - speedscale
      - kraken-ebpf-1772041112
      - kraken-speedctl-windows
      - speedscale-test-simple
      - kraken-2250193928-replay-loadtest
      - kraken-generator-perf-sla-1764779894
      - kraken-generator-perf-sla-1764774731
  view:
    active: v1/pods speedscale
  featureGates:
    nodeShell: false
  proxy: null
