k9s:
  cluster: minikube
  namespace:
    active: microservices
    lockFavorites: false
    favorites:
      - echo
      - smart-replace-demo
      - microservices
      - speedscale
      - grpc
      - default
  view:
    active: v1/namespaces
  featureGates:
    nodeShell: false
  proxy: null
