k9s:
  cluster: minikube
  namespace:
    active: smart-replace-demo
    lockFavorites: false
    favorites:
      - smart-replace-demo
      - microservices
      - speedscale
      - grpc
      - default
  view:
    active: v1/pods smart-replace-demo
  featureGates:
    nodeShell: false
  proxy: null
