k9s:
  cluster: arn:aws:eks:us-east-1:853014245683:cluster/staging-sstenant-eks-cluster
  namespace:
    active: default
    lockFavorites: false
    favorites:
      - sstenant-elastic
      - default
  view:
    active: v1/namespaces
  featureGates:
    nodeShell: false
  proxy: null
