k9s:
  cluster: arn:aws:eks:us-east-1:880246755038:cluster/prod-sstenant-eks-cluster
  namespace:
    active: default
    lockFavorites: false
    favorites:
      - sstenant-001636
      - sstenant-000073
      - all
      - sstenant-000072
      - sstenant-001318
      - default
      - sstenant-000202
  view:
    active: v1/namespaces
  featureGates:
    nodeShell: false
  proxy: null
