k9s:
  cluster: do-nyc1-dev-decoy
  namespace:
    active: beta-services
    lockFavorites: false
    favorites:
      - smart-replace-demo
      - speedscale
      - beta-services
      - microservices
      - default
  view:
    active: v1/secrets beta-services
  featureGates:
    nodeShell: false
  proxy: null
